name: QA

on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
